#+TITLE: Learning Exercise: Post-Money SAFE

* Background

https://www.ycombinator.com/documents/

* How Complex Are SAFEs?

People like to say SAFEs become a hairball after a startup has done more than a few. Is that true? Does the complexity of SAFEs scale linearly, quadratically, or exponentially? Let's find out.

* Conversion

What does the cap table look like at various stages of conversion -- before, during, after?

* Multiple Variants of SAFEs

Four different standard SAFE templates are given. This is good for us, because it gives four points in configuration space, from which we can determine dimensions.

#+begin_src haskell

  conversion :: SAFEinstrument -> Event SeriesA -> PercentageOwnership

  data SAFEinstrument = MkSafe { discount :: Maybe Int
                               , post_cap :: Maybe Int
                               , invested :: Int
                               , mfn      :: Bool -- "Most Favoured Nation"
                                 -- option to transform to a subsequent SAFEinstrument
                               }

  -- should be a NonEmptyList
  data VersionedObject a = VO [(Date, a)] -- where "snd $ head a" is the current thing

  data Event

  data Definition

  type Assertion = WorldState -> Bool

  data Representation = Rep Party Assertion

  data Modal = DeonticModal Party MayMustShant Action Deadline
             | EpistemicModal Party WorldState
             | TemporalModal
           
  faqConversion :: SAFEinstrument -> Scenario (Event SeriesA 10000000) -> WhatHappens

  --                if              then  else
  type ModalGraph = Modal (ThenElse Modal Modal)
                  | Breach    -- exit(-1), talk to a judge
                  | Fulfilled -- exit(0), all done

  data Boilerplate = Boilerplate String

  data MetaRule = MetaRule MetaRule MetaRule

  data IfThen = Upon Event Modal

  liquidityEvent = Upon liquidityEvent (EpistemicModal "send notice to Investor advising a liquidity event is happening")
    >> (DeonticModal Investor MAY RespondToEmail $ Left  (Response "yes Please" >> DeonticModal (Company MUST Pay X))
                                                   Right (Response "no thanks"  >> DeonticModal (Company MUST Pay Y))
                                                   )
     

  -- 	(b) Liquidity Event. If there is a Liquidity Event before the
  -- 	termination of this Safe, this Safe will automatically be
  -- 	entitled (subject to the liquidation priority set forth in
  -- 	Section 1(d) below) to receive a portion of Proceeds, due and
  -- 	payable to the Investor immediately prior to, or concurrent
  -- 	with, the consummation of such Liquidity Event, equal to the
  -- 	greater of (i) the Purchase Amount (the “Cash-Out Amount”) or
  -- 	(ii) the amount payable on the number of shares of Common
  -- 	Stock equal to the Purchase Amount divided by the Liquidity
  -- 	Price (the “Conversion Amount”).

  --                                     If any of the Company’s
  -- 	securityholders are given a choice as to the form and amount
  -- 	of Proceeds to be received in a Liquidity Event, the Investor
  -- 	will be given the same choice, provided that the Investor may
  -- 	not choose to receive a form of consideration that the
  -- 	Investor would be ineligible to receive as a result of the
  -- 	Investor’s failure to satisfy any requirement or limitation
  -- 	generally applicable to the Company’s securityholders, or
  -- 	under any applicable laws.

#+end_src

* Answering questions

** How much do I get?

** See the FAQ questions

- can we formalize the questions and the answers?
- can we obtain answers from the questions and the instrument?

* Test Cases

| U | Scenario | Investment Amount | Post Money Valuation Cap | Discount | Option Pool | Series A Raise | Series A Pre-Money Val | Outcome     |
|---+----------+-------------------+--------------------------+----------+-------------+----------------+------------------------+-------------|
| 1 | e.g. 1   |            100000 |                     none |        0 |        none |                |                1000000 |             |
| 2 | II.1     |            200000 |                  4000000 |        0 |           0 |                |                        |             |
| 3 | II.1     |            800000 |                  8000000 |        0 |        0.10 |        5000000 |               15000000 | x * (1 - y) |


* Learning Objectives
** Sections of Contracts -- Types of Contract Language
*** Parameters
*** Events
*** Definitions
**** Note the evaluation of a Dividend Amount requires quite a lot of calling context.
*** Representations by Party
*** Deontics
called, in the SAFEs, "Miscellaneous"
*** Boilerplate incantations
** Transformators and Combinators
*** Hypotheticals and Counterfactuals
*** Logging Conversions of State Over Time
** Mathematical Formulae
*** constraint solving
(pre-money safes needed to be solved as a system of linear equations)
