#+TITLE: EU Regulations for OTC Derivatives

* The Tender

In early 2020, the European Union [[https://etendering.ted.europa.eu/cft/cft-display.html?cftId=6051][announced a tender]] for machine-readable and -executable regulations for regulatory reporting.

Here, we study a fragment of the regulations of interest.

* The Source Regulations

https://www.legislation.gov.uk/eur/2012/648/title/ii/2019-10-31

TITLE II

CLEARING, REPORTING AND RISK MITIGATION OF OTC DERIVATIVES

Article 4

Clearing obligation

1. Counterparties shall clear all OTC derivative contracts pertaining to a class of OTC derivatives that has been declared subject to the clearing obligation in accordance with Article 5(2), if those contracts fulfil both of the following conditions:

   a. they have been concluded in one of the following ways:

      1. between two financial counterparties that meet the conditions set out in the second subparagraph of Article 4a(1);
      2. between a financial counterparty that meets the conditions set out in the second subparagraph of Article 4a(1) and a non-financial counterparty that meets the conditions set out in the second subparagraph of Article 10(1);
      3. between two non-financial counterparties that meet the conditions set out in the second subparagraph of Article 10(1);
      4. between, on the one side, a financial counterparty that meets the conditions set out in the second subparagraph of Article 4a(1) or a non-financial counterparty that meets the conditions set out in the second subparagraph of Article 10(1), and, on the other side, an entity established in a third country that would be subject to the clearing obligation if it were established in the Union;
      5. between two entities established in one or more third countries that would be subject to the clearing obligation if they were established in the Union, provided that the contract has a direct, substantial and foreseeable effect within the Union or where such an obligation is necessary or appropriate to prevent the evasion of any provisions of this Regulation; and

   b. they are entered into or novated on or after the date on which the clearing obligation takes effect, provided that, on the date they are entered into or novated, both counterparties meet the conditions set out in point (a).

* As a DocAssemble Interview

If you [[https://docassemble.org/docs/docker.html][boot up a DocAssemble container]] and paste this into the Example Playground, it should work:

#+begin_src yaml
metadata:
  title: Title II, Article 4, Section 1
  short title: 4.1
  comment: Does a derivative contract need to be cleared?
---
generic object: Individual
mandatory: True
question: |
  Parties ${ do_or_not } need to clear this contract.
subquestion: |
  This contract ${ does_or_not } ${ trigger } a clearing obligation.

  ${basis}

attachments:
  - name: Information Sheet
    filename: info_sheet
    content: |
        ${basis}
---
yesno: party_a.isfin
question: Is either of the parties a financial counterparty that meets the conditions set out in the second subparagraph of Article 4a(1)?
---
yesno: party_b.isfin
question: Is the other party a financial counterparty that meets the conditions set out in the second subparagraph of Article 4a(1)?
---
yesno: party_a.thirdCountryEntity
question: Is one of the parties established in a third country?
---
yesno: party_a.counterfactual_subject
question: Would that third-country party be subject to the clearing obligation if it were established in the Union?
---
yesno: party_a.notfin
question: Is either of the parties a non-financial counterparty that meets the conditions set out in the second subparagraph of Article 10(1)?
---
yesno: party_b.notfin
question: Is the other party a non-financial counterparty that meets the conditions set out in the second subparagraph of Article 10(1)?
---
yesno: party_b.thirdCountryEntity
question: Is the other party established in a third country?
---
yesno: party_b.counterfactual_subject
question: Would that other third-country party be subject to the clearing obligation if it were established in the Union?
---
yesno: effectInEU
question: Does the contract have a direct, substantial, and foreseeable effect within the Union?
---
yesno: anti_evasion
question: Would a clearing obligation be necessary or appropriate to prevent the evasion of any provisions of this Regulation?
---
code: |
  if ((party_a.isfin  and party_b.isfin) or
      (party_a.isfin  and party_b.notfin) or
      (party_a.notfin and party_b.notfin) or
      ( (party_a.isfin or party_a.notfin) and party_b.third ) or
      (  party_a.third and party_b.third and ( effectInEU or anti_evasion ) )):
    do_or_not, does_or_not, trigger = "do", "", "triggers"
  else:
    do_or_not, does_or_not, trigger = "do not", "does not", "trigger"
---
code: |
  if party_a.thirdCountryEntity and party_a.counterfactual_subject:
    party_a.third = True
  else:
    party_a.third = False
  if party_b.thirdCountryEntity and party_b.counterfactual_subject:
    party_b.third = True
  else:
    party_b.third = False
---
code: |
  if party_a.isfin and party_b.isfin:
    basis = "Rule 1 -- both are 4a(1) financial counterparties."
  elif party_a.isfin and party_b.notfin:
    basis = "Rule 2 -- one is a 4a(1) financial counterparty, the other is a 10(1) non-financial counterparty."
  elif party_a.notfin and party_b.notfin:
    basis = "Rule 3 -- both are 10(1) non-financial counterparties."
  elif (party_a.notfin or party_a.notfin) and party_b.third:
    basis = "Rule 4 -- one party is either a 4a(1) or 10(1) counterparty, and the other is a third-country entity which would be, if it were in the Union."
  elif party_a.third and party_b.third and effectInEU:
    basis = "Rule 5 -- both parties are third-country entities which would be subject to the clearing obligation if they were in the Union, and the contract has a direct, substantial, and foreseeable effect within the Union."
  elif party_a.third and party_b.third and anti_evasion:
    basis = "Rule 5 -- both parties are third-country entities which would be subject to the clearing obligation if they were in the Union, and such an obligation is necessary or appropriate to prevent the evasion of any provisions of this Regulation."
  else:
    basis = "Trigger conditions do not apply."
---
objects:
  - party_a: Individual
  - party_b: Individual
#+end_src

* As a DMN table

The essential logic is:

#+NAME: 41a conditions
| F | party.a       | party.b | other                    | return |
|---+---------------+---------+--------------------------+--------|
| 1 | isfin         | isfin   | -                        | TRUE   |
| 2 | isfin         | notfin  | -                        | TRUE   |
| 3 | notfin        | notfin  | -                        | TRUE   |
| 4 | isfin, notfin | third   | -                        | TRUE   |
| 5 | third         | third   | effectInEU, anti_evasion | TRUE   |

Here the expressions in the body cells are not directly matched against the object identified in the column header. Instead, they are predicate methods: you may think of them as ~party.a.isfin()~ returning a Bool which is then used in the decision table.

In our extension to DMN syntax we might indicate that with a type annotation of ~: predicate~.

In a language like Alloy we would take advantage of a relational syntax to show that party a vs party b are swappable, particularly with respect to rules 2 and 4. We don't want to bind so tightly to A and B that we fail to match a situation where ~A~ is ~notfin~, and ~B~ is ~isfin~.

* In L4-Vapourware

Here's what the regulation might look like in a possible syntax for L4:

#+begin_src text
  RULE    4.1 /@/ en"Title II" // en"Article 4" // en"Clearing Obligation" //> en"Section 1"
  ALIAS   subj(clearOb) -- "subject to clearing obligation"
  PARTIES P @ en"Counterparties"
  MUST    clear all dc:Contract
  WHERE ( dc ~ (derivative ~ declared (subj(clearObj) ~~ rule 5.2))
        , partyConditions @ (
          LET      isfin =    financial & rule 4a.1.2
                  notfin = nonfinancial & rule 10.1
                   third = thirdCountryEntity & counterfactual(this{thirdCountryEntity={return False}}, subj(clearOb))
              effectInEU = effectByGeography Geo.EU ~ [direct, substantial & foreseeable]
           IN dc ~
                 | F | party.a : pred | party.b : pred | other          | return |
                 |---+----------------+----------------+----------------+--------|
                 | 1 | isfin          | isfin          | -              | TRUE   |
                 | 2 | isfin          | notfin         | -              | TRUE   |
                 | 3 | notfin         | notfin         | -              | TRUE   |
                 | 4 | isfin, notfin  | third          | -              | TRUE   |
                 | 5 | third          | third          | effectInEU,    | TRUE   |
                 |   |                |                | anti_evasion   |        |
        )
        & ( dcDate @ ( dc.date | dc.novation.date ) >= clearOb.effectiveDate
          & asOf(dcDate, partyConditions) )
        )
#+end_src

Note that the DMN table is inlined directly into the DSL.

What does the syntax mean?
- The tilde (~) acts as a heavily overloaded "match" operator.
- We support counterfactual reasoning by way of Haskell's record-modification syntax -- the definition of ~third~ treats ~this.thirdCountryEntity()~ as an overrideable instance prototype method.
- Conjunctive and disjunctive lists use syntax that looks like ~[,,,&]~ and ~[,,,|]~ as syntactic sugar for ~all [,,,,]~ and ~any [,,,,]~ respectively.
- We use an alias in the rule definition because we observe recursion in the "subject to the clearing obligation" condition in rules 4 and 5 relating to third-country entities. L4 probably needs to impose some sort of bounded recursion or constraint satisfaction logic to deduce/reduce a decidable, satisfiable interpretation of the rules.

* LegalRuleML

LegalRuleML offers a way to link back to the source regulations:

#+begin_src xml
<lrml:LegalReferences
 xmlns:appex="http://docs.oasis-open.org/legalruleml/examples/compactified/"
 refType="http://example.legalruleml.org/lrml#LegalSource">
  <lrml:LegalReference refersTo=".11"
   refID="ECLI:EU:C:2012:648"
   refIDSystemName="Regulation (EU) No 648/2012 of the European Parliament and of the Council of 4 July 2012 on OTC derivatives, central counterparties and trade repositories (Text with EEA relevance)"
   refIDSystemSource="http://www.legislation.gov.uk/eur/2012/648/title/ii/2019-10-31"/>
</lrml:LegalReferences>
#+end_src

We'll talk about expressing the semantics of the rules in LegalRuleML separately.

* The Underlying Ontology, or Types

In some monstrous hybrid of Typescript and Haskell we might express the class structure this way:

#+begin_src typescript
  type CountryCode = string;

  const euCountries = { "2020": "BE EL LT PT BG ES LU RO CZ FR HU SI DK HR MT SK DE IT NL FI EE CY AT SE IE LV PL".split(" ") }

  class Party {
    Country       : CountryCode;
    IsFin         : boolean;
    NotFin        : boolean;
    Rule_4a_1_2   : boolean;
    Rule_10_1     : boolean;
    thirdCountryEntity(countries) : boolean { return not countries.includes(this.country) }
  }

  interface EffectType { direct      : boolean;
                         substantial : boolean;
                         foreseeable : boolean; }

  class Contract {
    p=party=parties: Party[];
    effectByGeography : region -> EffectType;
  }
#+end_src

There are other ways to formalize this; can a party be said to be subject to a clearing obligation -- /independent of its counterparty or contract/? In this case, yes; knowing its ~IsFin~ or ~NotFin~ status is sufficient to deliver a ~True~. And that way we know the recursive definition in rules 4 and 5 are safe.

But it leads one to ask: What is the type of a clearing obligation? Does it attach to a party? Or to a contract?

* Natural Language Generation

A challenge for our NLG team: develop GF-based code that reads the DMN table and outputs the original regulations. Along the way, evolve the ontology so that it contains all the information needed to build the relevant GF grammar.

