name:                aotearoa
version:             0.1.0.0
github:              "mengwong/aotearoa"
license:             BSD3
author:              "Meng Weng Wong"
maintainer:          "mengwong@legalese.com"
copyright:           "Legalese Pte. Ltd."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mengwong/aotearoa#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- regex-compat
- mtl
- boxes
- text
- matrix
- split
- directory

library:
  source-dirs: src

executables:
  aotearoa-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aotearoa

tests:
  aotearoa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aotearoa
