{-# LANGUAGE OverloadedStrings, DuplicateRecordFields, QuasiQuotes #-}
{-# OPTIONS_GHC -F -pgmF=record-dot-preprocessor #-}

-- DO NOT EDIT THIS FILE!
-- direct edits will be clobbered.
-- 
-- this file is autogenerated!
-- open the parent README.org in emacs and hit   C-c C-v t   to regenerate this file.

module HelloWorld where
import Data.Map
import Data.Maybe
import Data.Tree
import Data.Time.Calendar
import Data.Time.Format.ISO8601


legalDates night = [ sameDay night, nextDay night ]
  where sameDay x = x
        nextDay x = addDays 1 x
